Want basic logging support for logging output and other side-effects

diff --git a/libexec/bats b/libexec/bats
--- a/libexec/bats
+++ b/libexec/bats
@@ -7,7 +7,7 @@ version() {
 
 usage() {
   version
-  echo "Usage: bats [-c] [-p | -t] <test> [<test> ...]"
+  echo "Usage: bats [-c] [-l <logfile>] [-p | -t] <test> [<test> ...]"
 }
 
 help() {
@@ -18,6 +18,7 @@ help() {
   echo
   echo "  -c, --count    Count the number of test cases without running any tests"
   echo "  -h, --help     Display this help message"
+  echo "  -l  --log      Set path to log file used by all tests with logit calls"
   echo "  -p, --pretty   Show results in pretty format (default for terminals)"
   echo "  -t, --tap      Show results in TAP format"
   echo "  -v, --version  Display the version number"
@@ -98,8 +99,7 @@ for arg in "$@"; do
     arguments[${#arguments[*]}]="$arg"
   fi
 done
-
-unset count_flag pretty
+unset count_flag pretty logfile
 count_flag=''
 pretty=''
 [ -t 0 ] && [ -t 1 ] && pretty="1"
@@ -115,6 +115,17 @@ if [[ "${#options[@]}" -ne '0' ]]; then
     "v" | "version" )
       version
       exit 0
+      ;;
+    "l" | "log" )
+      # If -l | --log option was passed, the argument following it
+      # is assumed to be name of logfile, i.e. relative or absolute
+      # path.
+      logfile=${arguments[0]}
+      if ! touch "${logfile}" >/dev/null 2>&1 ; then
+        unset logfile
+        echo "error: unable to read log file, path is invalid" >&2
+      fi
+      arguments=(${arguments[@]:1}) # Shift arguments by one
       ;;
     "c" | "count" )
       count_flag="-c"
@@ -132,6 +143,9 @@ if [[ "${#options[@]}" -ne '0' ]]; then
     esac
   done
 fi
+
+if [ -n "${logfile}" ]; then export BATS_LOGFILE_PATH="${logfile}"; fi
+echo "opts=${options[@]} args=${arguments[@]}"
 
 if [ "${#arguments[@]}" -eq 0 ]; then
   usage >&2
